### PR TITLE
Use semantic-ui as an UI library

### PR DESCRIPTION
**Pull request by brnrdog**
I'm testing the [Semantic UI](http://semantic-ui.com/) as an user interface library. 

The goal is to have a well defined set of user interface components available, so everyone can develop their features without a deep knowledge about the css and js implementation – so everyone can be independent. All the components are very well documented in Semantic UI website.

This is an experiment. I'm just trying out. 
Feel free to comment about it. Feedback is more than appreciated.

Feedback is love :heart:

### CODE REVIEW

**Comment by brnrdog** [comment]
There are some downsides to Semantic UI. But the main one is that it's [less](http://lesscss.org/) powered. I prefer sass, and rails too.

**Comment by IgorMarques** [comment]
Looking forward to it :+1:

**Comment by brnrdog** [comment]
At least there is a gem with a sass port of semantic-ui to work with rails :+1:

**Comment by brnrdog** [comment]
This framework is a freaking hell to extend/customize in Rails :rage2:

**Comment by fmarquesfilho** [comment]
Just a off topic comment: You guys should write your bachelor theses in
English. How does that sound?

Em Sex, 28 de ago de 2015 20:25, Bernardo Gurgel de Faria <
notifications@github.com> escreveu:

**Comment by IgorMarques** [comment]
@fmarquesfilho I think the overhead of writing in english (for me, at the moment) would be too big. I can maybe translate it someday (after presenting), but I'd feel more comfortable and would be faster writing it first in portuguese.  Sorry :(

**Comment by IgorMarques** [comment]
@bernardogfilho So why keep it?

**Comment by brnrdog** [comment]
The same for me, @fmarquesfilho. It would be cool, but only if I had more time to invest. Unfortunately it's not the case.

**Comment by brnrdog** [comment]
I'm still figuring out how the customization works, @IgorMarques. It's really opinionated, the best way to change some colors, for example, is changing the variables, because the classes are defined as something like:

``` css
.ui.component > .subcomponent > .element .another-element {
...
}
```

So the only way to override this class, is to overriding all this chain of classes :rage3:

**Comment by brnrdog** [comment]
Posso fazer merge?

**Pull request merged**
