### PR TITLE
Omniauth

### PR DESCRIPTION
**Pull request by IgorMarques**
Add an incomplete omniauth login feature. It still missing the persistency step (I guess), with the following error:

screenshot 2015-08-28 23 58 00

If someone could fix this before the merge, it would be awesome.

**IMPORTANT: If you wanna run the code, check the instructions at the new README**

### CODE REVIEW

**Comment by brnrdog** [comment]
When I try to login, I get a 404 from Github.

**Comment by IgorMarques** [comment]
@bernardogfilho have you setted your .env variables according to the new README?

**Comment by brnrdog** [comment]
No, I didn't know about it :+1:

**Comment by brnrdog** [comment]
@IgorMarques, I think your problem was related to your mongodb server instance. Maybe you forgot to start the server? I got working here. I made some little modifications and I added a `current_user` helper method.

**Comment by IgorMarques** [comment]
I don't have a mongodb server here. Good to know that's the problem!

**Comment by brnrdog** [comment]
Now it's working without problems :+1:

**Comment by IgorMarques** [comment]
Awesome. Good to merge or do you plan to add more stuff?

**Comment by brnrdog** [comment]
I think it's good for now.

**Pull request merged**
